inherit_from: .rubocop_todo.yml

require:
  - solidus_dev_support/rubocop

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*
    - spec/features/**/*

Rails/SkipsModelValidations:
  Enabled: false
